logging:
  level:
    ROOT: INFO
    org.ylzl.eden: DEBUG
    org.ylzl.eden.gateway.infrastructure: DEBUG

spring:
  # 缓存数据库
  redis:
    #    database: 1
    #    host: localhost
    #    port: 6379
    password: puyiwm
    timeout: 5000
    cluster:
      nodes: 10.2.2.45:6379,10.2.2.48:6379,10.2.2.47:6379,10.2.2.47:6380,10.2.2.47:6381,10.2.2.47:6382
  # 模板引擎
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://10.2.2.47:9411
    discovery-client-enabled: true
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1
    async:
      configurer:
        enabled: false # Bugfix: 兼容 Spring 高版本
